### ISSUE TITLE
The Places area is empty and drak mode not work

### ISSUE THREAD

**Issue by ClayStan** [f35f22fan/Cornus#3]
you can view : https://i.loli.net/2021/03/08/K8ThCDeFWU6vXig.png
I tested in Debian unstable and arch linux , Gnome DE
And I used the dark theme, but it didn't work too.

**Comment by f35f22fan** [comment]
So,
I rebooted to another OS and
1) the places area did show up (screenshot attached)
2) the dark mode didn't kick in - since it's something Qt has to pick as it
does so under KDE (no extra effort done by my app) I'm guessing either your
Qt is old or it's a bug in the app.

Therefore: what Qt version are you using?
Can you run it from the terminal and see if it prints out any errors?

**Comment by f35f22fan** [comment]
by "old qt & bug in my app" I wasn't referring to the dark mode but to the
places area not showing up.

**Comment by f35f22fan** [comment]
I should note that the app requires Linux 5.3+, I installed Debian but it ships with 4.19 and failed to start the gnome session, probably because it lacks drivers for my Radeon RX 570. I also tried installing arch but it's too complicated - when I booted from the ISO it dropped me to a command line and I lost interest in Arch.

**Comment by f35f22fan** [comment]
I tested in Fedora 33 Gnome - the dark theme kinda works - if you launch the app after the theme gets changed it picks the dark theme, otherwise you just have to restart the app.
The places pane also works. Don't know why it doesn't show up on your PC.

**Comment by ClayStan** [comment]
I test it again, I test it in virtual machine, the Place panel can show my disks, but Physical machine can't, same DE, same systemd, debian unstable , The difference is that the virtual disk of virtual machine is in /dev/sd*, but my physical machine uses solid-state disk, which is in /dev/nvme *, I mount a mechanical hard disk on my physical machine, and the place panel can be displayed

**Comment by ClayStan** [comment]
https://github.com/f35f22fan/Cornus/blob/7f31a19b3df88fca156f1930d076492b0b7fb87e/gui/SidePaneModel.cpp#L118

**Comment by ClayStan** [comment]
https://github.com/f35f22fan/Cornus/blob/7f31a19b3df88fca156f1930d076492b0b7fb87e/gui/SidePaneModel.cpp#L98

**Comment by f35f22fan** [comment]
Thank you, I don't have an NVME device so I'll google around and see if I can implement it blindly.

**Comment by ClayStan** [comment]
https://github.com/f35f22fan/Cornus/pull/4
